services:
  tg-channel-parser:
    image: ghcr.io/damirlut/tg-channel-parser:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: tg-channel-parser
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/app/pb_data
    environment:
      TZ: Europe/Moscow
      HTTP_PROXY: "${HTTP_PROXY:-}"
      HTTPS_PROXY: "${HTTPS_PROXY:-}"
      NO_PROXY: "${NO_PROXY:-}"
    restart: unless-stopped

volumes:
  pb_data: